### ISSUE TITLE
Do you support Collections?

### ISSUE THREAD

**Issue by ricardopolo** [Code52/pretzel#195]
http://jekyllrb.com/docs/collections/

**Comment by ricardopolo** [comment]
Yes you do.

This works
````yaml
pretzel:
    engine: liquid
collections:
- portfolioContent
````

This does not works:
````yaml
pretzel:
    engine: liquid
    collections:
    - portfolioContent
````
